---

- debug: var=recreate_keys
# tasks file for ansible-role-sshkeypair
#- debug: var=hostvars[inventory_hostname].facter_gid
- stat: path="{{ ssh_key_files_dir }}"
  register: st

- name: Create Output Directory for SSH Keys
  file:
    state: directory
    path: "{{ ssh_key_files_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user_gid }}"
    mode: 0755
  when: not st.stat.exists

- stat: path="{{ ssh_key_files_dir }}/{{ ssh_key_file_name }}"
  register: st

- name: Remove existing private key file  if recreate is designated and file already present
  file:
    path: "{{ ssh_key_files_dir }}/{{ ssh_key_file_name }}" 
    state: absent
  when: st.stat.exists and recreate_keys

- name: Remove existing public key file  if recreate is designated and file already present
  file:
    path: "{{ ssh_key_files_dir }}/{{ ssh_key_file_name }}.pub"
    state: absent                                                                                                                                                                 
  when: st.stat.exists and recreate_keys

- name: Create KeyPair
  register: created
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: "{{ ssh_key_files_dir }}/{{ ssh_key_file_name }}"
    state: present
  when: not st.stat.exists or recreate_keys

# only encrypt if the file is not encrypted and was newly created ie. vault view failed
# do not encrypt a file that already exists and was unencrypted by the user for use.
- name: vault the created private key
  shell: ansible-vault encrypt "{{ ssh_key_files_dir }}/{{ ssh_key_file_name }}"
  when: not created|skipped
